chore: Update code for reuse v0.5
ansys/pre-commit-hooks pull request #263
Opened 2024-12-05 17:27 UTC by klmcadams

- Reordered code to be in chronological order
- Fix how years are being checked & updated in files
- Create separate functions to add and update the headers (which are called in the recursive & non-recursive file checks)
- Check if file contains reuse information. If not, add the header to the file. Otherwise, update the header

2024-12-09 07:46 UTC, RobPasMue commented
I'll have a look at this asap, but probably not today! Sorry!

2024-12-11 11:44 UTC, RobPasMue requested changes
Looking good - but we really need to move away from os.path...

2024-12-11 11:44 UTC, RobPasMue commented on src/ansys/pre_commit_hooks/add_license_headers.py
> +
Why not use pathlib? It will handle the paths properly based on your OS

2024-12-11 11:44 UTC, RobPasMue commented on src/ansys/pre_commit_hooks/add_license_headers.py
> +
Also, with a pathlib.Path object you can request at any moment the absolute path. So no need to have the dedicated function to get "full" paths. Just call the absolute path method in the Path object

2024-12-11 11:44 UTC, RobPasMue commented on src/ansys/pre_commit_hooks/add_license_headers.py
> +    hook_license_file = os.path.join(hook_loc, "assets", "LICENSES", f"{DEFAULT_LICENSE}.txt")
```suggestion
    hook_license_file = hook_loc / "assets" / "LICENSES" / f"{DEFAULT_LICENSE}.txt"
```
Path objects can be chained like this... avoid using ``os.path`` overall

2024-12-11 11:44 UTC, RobPasMue commented on src/ansys/pre_commit_hooks/add_license_headers.py
> +    hook_license_file = os.path.join(hook_loc, "assets", "LICENSES", f"{DEFAULT_LICENSE}.txt")
This applies everywhere

2024-12-17 15:10 UTC, klmcadams commented
I will make a separate PR to address the os to pathlib conversions

2024-12-17 15:24 UTC, merged